sudo: false
os:
 - linux
 - osx
language: d
d:
 - ldc
 - ldc-beta
 - ldc-1.8.0
 - ldc-1.4.0
 - dmd
 - dmd-nightly
 - dmd-2.079.1
 - dmd-2.078.3
script:
 - dub test --compiler=${DC} --build=unittest-cov
matrix:
 exclude:
  - {os: osx, d: ldc-1.4.0}  
after_success:
 - bash <(curl -s https://codecov.io/bash)
